### ISSUE TITLE
Incompatibility with dropwizard 2

### ISSUE THREAD

**Issue by ochedru** [gini/dropwizard-gelf#31]
The latest version fails to load with dropwizard 2 because of a change in the signature of method `io.dropwizard.logging.AbstractAppenderFactory.getFilterFactories`:
```
java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableList net.gini.dropwizard.gelf.logging.GelfAppenderFactory.getFilterFactories()'
	at net.gini.dropwizard.gelf.logging.GelfAppenderFactory.build(GelfAppenderFactory.java:250)
	at io.dropwizard.logging.DefaultLoggingFactory.configureLoggers(DefaultLoggingFactory.java:309)
	at io.dropwizard.logging.DefaultLoggingFactory.configure(DefaultLoggingFactory.java:158)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:83)
	at io.dropwizard.cli.Cli.run(Cli.java:79)
	at io.dropwizard.Application.run(Application.java:94)
```
If dropwizard-gelf is built with dropwizard 2.0.0, the problem goes away.

**Comment by kchamp21** [comment]
bump this request, we are running to the same issue
a release with fix for the above would be greatly appreciated
currently this is blocking us from upgrading to DW 2.0.10

**Comment by joschi** [comment]
@ochedru @kchamp21 @splatch Thanks for reporting and fixing this! 👍

We've released a new version of dropwizard-gelf and it should be soon available on Maven Central.

**Comment by kchamp21** [comment]
Thanks a lot for the quick turn around!
